# Knowledge-hub data-plane policies. Both attach to aws_iam_role.knowledge_hub.
#
# Neither identifier is derivable here — Neptune's cluster_resource_id is
# generated by AWS, and the text cache bucket carries a random_id suffix — so
# both come in as variables fed from nx-infra-tf's outputs at the env root.
# That is not a module cycle: nx-infra-tf consumes role ARNs from here, but the
# resources on each side are disjoint (aws_s3_bucket and aws_neptune_cluster
# depend on nothing from this module), and Terraform's graph is resource-level
# after module flattening.
#
# The text cache bucket name is required rather than wildcarded — see the
# precondition below.

locals {
  kh_neptune_create    = local.knowledge_hub_create && var.enable_knowledge_hub_neptune_access
  kh_text_cache_create = local.knowledge_hub_create && var.enable_knowledge_hub_text_cache_access

  # neptune-db ARNs key off cluster_resource_id (cluster-XXXX...), which is not
  # derivable from the cluster identifier and has no data source to look it up.
  kh_neptune_resource = var.knowledge_hub_neptune_cluster_resource_id != "" ? var.knowledge_hub_neptune_cluster_resource_id : "*"

  kh_text_cache_bucket = var.knowledge_hub_text_cache_bucket_name
}

################################################################################
# Neptune IAM-auth connect
################################################################################

data "aws_iam_policy_document" "knowledge_hub_neptune" {
  count = local.kh_neptune_create ? 1 : 0

  statement {
    sid    = "NeptuneDataAccess"
    effect = "Allow"
    actions = [
      "neptune-db:connect",
      "neptune-db:ReadDataViaQuery",
      "neptune-db:WriteDataViaQuery",
      "neptune-db:DeleteDataViaQuery",
      "neptune-db:GetEngineStatus",
      "neptune-db:GetQueryStatus"
    ]
    resources = ["arn:${local.partition}:neptune-db:${var.region}:${data.aws_caller_identity.current[0].account_id}:${local.kh_neptune_resource}/*"]
  }
}

resource "aws_iam_policy" "knowledge_hub_neptune" {
  count  = local.kh_neptune_create ? 1 : 0
  name   = var.knowledge_hub_neptune_policy_name != "" ? var.knowledge_hub_neptune_policy_name : "${var.knowledge_hub_role_name}-neptune-connect"
  policy = data.aws_iam_policy_document.knowledge_hub_neptune[0].json
  tags   = var.tags
}

resource "aws_iam_role_policy_attachment" "knowledge_hub_neptune" {
  count      = local.kh_neptune_create ? 1 : 0
  role       = aws_iam_role.knowledge_hub[0].name
  policy_arn = aws_iam_policy.knowledge_hub_neptune[0].arn
}

################################################################################
# Text content cache — read only
################################################################################

# knowledge-hub reads the text cache that content-service writes; it never
# writes there, so GetObject only.
data "aws_iam_policy_document" "knowledge_hub_text_cache_read" {
  count = local.kh_text_cache_create ? 1 : 0

  statement {
    sid       = "TextContentCacheRead"
    effect    = "Allow"
    actions   = ["s3:GetObject"]
    resources = ["arn:${local.partition}:s3:::${local.kh_text_cache_bucket}/*"]
  }
}

resource "aws_iam_policy" "knowledge_hub_text_cache_read" {
  count  = local.kh_text_cache_create ? 1 : 0
  name   = var.knowledge_hub_text_cache_policy_name != "" ? var.knowledge_hub_text_cache_policy_name : "${var.knowledge_hub_role_name}-text-cache-read"
  policy = data.aws_iam_policy_document.knowledge_hub_text_cache_read[0].json
  tags   = var.tags

  lifecycle {
    precondition {
      condition     = var.knowledge_hub_text_cache_bucket_name != ""
      error_message = "knowledge_hub_text_cache_bucket_name is required when enable_knowledge_hub_text_cache_access = true. Pass nx-infra-tf's text_content_cache_bucket_name output; the bucket carries a random_id suffix so the name cannot be derived here."
    }
  }
}

resource "aws_iam_role_policy_attachment" "knowledge_hub_text_cache_read" {
  count      = local.kh_text_cache_create ? 1 : 0
  role       = aws_iam_role.knowledge_hub[0].name
  policy_arn = aws_iam_policy.knowledge_hub_text_cache_read[0].arn
}
