# Knowledge-hub data-plane policies that used to live in nx-infra-tf.
#
# Both were there because the exact resource ARN is only knowable after the
# resource exists: Neptune's cluster_resource_id is generated by AWS, and the
# text cache bucket carries a random_id suffix. Wiring either back into this
# module would mean nx-iam-tf consuming an nx-infra-tf output while
# nx-infra-tf already consumes role ARNs from here.
#
# Instead both ARNs are constructed, the same way knowledge-hub's S3 Vectors
# policy already builds its bucket ARN from plan-time-known values. The cost is
# scope: without the generated identifier these fall back to an account-scoped
# wildcard. Pass the override variables to tighten them back to one resource.

locals {
  kh_neptune_create    = local.knowledge_hub_create && var.enable_knowledge_hub_neptune_access
  kh_text_cache_create = local.knowledge_hub_create && var.enable_knowledge_hub_text_cache_access

  # neptune-db ARNs key off cluster_resource_id (cluster-XXXX...), which is not
  # derivable from the cluster identifier and has no data source to look it up.
  kh_neptune_resource = var.knowledge_hub_neptune_cluster_resource_id != "" ? var.knowledge_hub_neptune_cluster_resource_id : "*"

  # Buckets in nx-infra-tf are named nvisionx-<key>-<random_id hex>, so the
  # suffix is unknowable here. A prefix wildcard grants nothing extra in
  # practice: cross-account GetObject needs the bucket policy to allow it too,
  # so a same-named bucket in another account is not reachable through this.
  kh_text_cache_bucket = var.knowledge_hub_text_cache_bucket_name != "" ? var.knowledge_hub_text_cache_bucket_name : "nvisionx-text-content-cache-*"
}

################################################################################
# Neptune IAM-auth connect
################################################################################

data "aws_iam_policy_document" "knowledge_hub_neptune" {
  count = local.kh_neptune_create ? 1 : 0

  statement {
    sid    = "NeptuneDataAccess"
    effect = "Allow"
    actions = [
      "neptune-db:connect",
      "neptune-db:ReadDataViaQuery",
      "neptune-db:WriteDataViaQuery",
      "neptune-db:DeleteDataViaQuery",
      "neptune-db:GetEngineStatus",
      "neptune-db:GetQueryStatus"
    ]
    resources = ["arn:${local.partition}:neptune-db:${var.region}:${data.aws_caller_identity.current[0].account_id}:${local.kh_neptune_resource}/*"]
  }
}

resource "aws_iam_policy" "knowledge_hub_neptune" {
  count  = local.kh_neptune_create ? 1 : 0
  name   = var.knowledge_hub_neptune_policy_name != "" ? var.knowledge_hub_neptune_policy_name : "${var.knowledge_hub_role_name}-neptune-connect"
  policy = data.aws_iam_policy_document.knowledge_hub_neptune[0].json
  tags   = var.tags
}

resource "aws_iam_role_policy_attachment" "knowledge_hub_neptune" {
  count      = local.kh_neptune_create ? 1 : 0
  role       = aws_iam_role.knowledge_hub[0].name
  policy_arn = aws_iam_policy.knowledge_hub_neptune[0].arn
}

################################################################################
# Text content cache — read only
################################################################################

# knowledge-hub reads the text cache that content-service writes; it never
# writes there, so GetObject only.
data "aws_iam_policy_document" "knowledge_hub_text_cache_read" {
  count = local.kh_text_cache_create ? 1 : 0

  statement {
    sid       = "TextContentCacheRead"
    effect    = "Allow"
    actions   = ["s3:GetObject"]
    resources = ["arn:${local.partition}:s3:::${local.kh_text_cache_bucket}/*"]
  }
}

resource "aws_iam_policy" "knowledge_hub_text_cache_read" {
  count  = local.kh_text_cache_create ? 1 : 0
  name   = var.knowledge_hub_text_cache_policy_name != "" ? var.knowledge_hub_text_cache_policy_name : "${var.knowledge_hub_role_name}-text-cache-read"
  policy = data.aws_iam_policy_document.knowledge_hub_text_cache_read[0].json
  tags   = var.tags
}

resource "aws_iam_role_policy_attachment" "knowledge_hub_text_cache_read" {
  count      = local.kh_text_cache_create ? 1 : 0
  role       = aws_iam_role.knowledge_hub[0].name
  policy_arn = aws_iam_policy.knowledge_hub_text_cache_read[0].arn
}
